import {
  Activity,
  Bell,
  Cpu,
  Droplets,
  Gauge,
  Radio,
  Thermometer,
  Video,
  Wifi,
  Zap,
} from 'lucide-react'
import { ActivityEvent, Device, MetricCard, ProjectLocation } from '@/types/iot'

export const navigationTabs = ['Overview', 'Devices', 'Activity'] as const

export const overviewMetrics: MetricCard[] = [
  {
    label: 'Active devices',
    value: '24',
    detail: '+3 this month',
    changeType: 'positive',
    icon: Cpu,
    color: 'text-sky-600',
    bg: 'bg-sky-50 dark:bg-sky-950/40',
  },
  {
    label: 'Online now',
    value: '21',
    detail: '87.5% of devices',
    changeType: 'positive',
    icon: Wifi,
    color: 'text-emerald-600',
    bg: 'bg-emerald-50 dark:bg-emerald-950/40',
  },
  {
    label: 'Events today',
    value: '1,284',
    detail: '+12.4% from yesterday',
    changeType: 'positive',
    icon: Bell,
    color: 'text-violet-600',
    bg: 'bg-violet-50 dark:bg-violet-950/40',
  },
  {
    label: 'Avg. temperature',
    value: '22.8°C',
    detail: 'Within target range',
    changeType: 'neutral',
    icon: Gauge,
    color: 'text-amber-600',
    bg: 'bg-amber-50 dark:bg-amber-950/40',
  },
]

export const initialDevices: Device[] = [
  {
    name: 'Temperature sensor',
    id: 'TH-2048',
    location: 'Main office',
    value: '23.4°C',
    status: 'Online',
    type: 'temperature',
    battery: '94%',
    lastUpdated: 'Just now',
    icon: Thermometer,
    color: 'text-sky-600',
    bg: 'bg-sky-50 dark:bg-sky-950/50',
  },
  {
    name: 'Air quality monitor',
    id: 'AQ-1032',
    location: 'Main office',
    value: 'Good (18 AQI)',
    status: 'Online',
    type: 'air_quality',
    battery: '88%',
    lastUpdated: '2m ago',
    icon: Activity,
    color: 'text-emerald-600',
    bg: 'bg-emerald-50 dark:bg-emerald-950/50',
  },
  {
    name: 'Power relay',
    id: 'PR-0891',
    location: 'Warehouse',
    value: 'On (2.4 kW)',
    status: 'Online',
    type: 'power',
    battery: '100% (AC)',
    lastUpdated: '5m ago',
    icon: Zap,
    color: 'text-amber-600',
    bg: 'bg-amber-50 dark:bg-amber-950/50',
  },
  {
    name: 'Humidity controller',
    id: 'HC-3310',
    location: 'Greenhouse',
    value: '64% RH',
    status: 'Online',
    type: 'humidity',
    battery: '76%',
    lastUpdated: '1m ago',
    icon: Droplets,
    color: 'text-cyan-600',
    bg: 'bg-cyan-50 dark:bg-cyan-950/50',
  },
  {
    name: 'Gateway repeater',
    id: 'GW-9014',
    location: 'Warehouse',
    value: '12 Connected',
    status: 'Online',
    type: 'pressure',
    battery: '100% (AC)',
    lastUpdated: '10s ago',
    icon: Radio,
    color: 'text-indigo-600',
    bg: 'bg-indigo-50 dark:bg-indigo-950/50',
  },
  {
    name: 'Security camera A1',
    id: 'CAM-5502',
    location: 'Greenhouse',
    value: 'Signal Weak',
    status: 'Warning',
    type: 'camera',
    battery: '31%',
    lastUpdated: '14m ago',
    icon: Video,
    color: 'text-rose-600',
    bg: 'bg-rose-50 dark:bg-rose-950/50',
  },
]

export const projectLocations: ProjectLocation[] = [
  {
    id: 'loc-1',
    name: 'Main office',
    deviceCount: 12,
    onlineCount: 12,
    status: 'operational',
  },
  {
    id: 'loc-2',
    name: 'Warehouse',
    deviceCount: 8,
    onlineCount: 8,
    status: 'operational',
  },
  {
    id: 'loc-3',
    name: 'Greenhouse',
    deviceCount: 4,
    onlineCount: 3,
    status: 'degraded',
  },
]

export const activityLogs: ActivityEvent[] = [
  {
    id: 'act-1',
    title: 'High temperature alert resolved',
    description: 'TH-2048 returned to optimal range (23.4°C). System auto-stabilized.',
    timestamp: '2 minutes ago',
    type: 'success',
    deviceId: 'TH-2048',
    deviceName: 'Temperature sensor',
    location: 'Main office',
  },
  {
    id: 'act-2',
    title: 'Low battery threshold triggered',
    description: 'Security camera A1 battery dropped below 35%. Recharge recommended.',
    timestamp: '14 minutes ago',
    type: 'warning',
    deviceId: 'CAM-5502',
    deviceName: 'Security camera A1',
    location: 'Greenhouse',
  },
  {
    id: 'act-3',
    title: 'Mesh network sync completed',
    description: 'Gateway GW-9014 synced 24 nodes with 0 packet drops.',
    timestamp: '42 minutes ago',
    type: 'info',
    deviceId: 'GW-9014',
    deviceName: 'Gateway repeater',
    location: 'Warehouse',
  },
  {
    id: 'act-4',
    title: 'Firmware auto-update v2.4.1',
    description: 'OTA firmware deployed successfully across 18 compatible sensor nodes.',
    timestamp: '2 hours ago',
    type: 'info',
    location: 'All Locations',
  },
  {
    id: 'act-5',
    title: 'Power relay schedule executed',
    description: 'Main irrigation switch PR-0891 turned ON according to daylight schedule.',
    timestamp: '4 hours ago',
    type: 'success',
    deviceId: 'PR-0891',
    deviceName: 'Power relay',
    location: 'Warehouse',
  },
]
